🔥 Python is working in Termux!
-------------------------------
Python Version     : 3.11.x
Operating System   : Linux
Release Version    : 4.x / 5.x Android kernel
Machine            : aarch64

Running a quick loop test:
Counting 1...
Counting 2...
Counting 3...
Counting 4...
Counting 5...

🎉 All tests completed!
